Controllers/PurchaseController.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Controllers
{
    // controller for creating the cart functionality
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public  PurchaseController (IPurchaseRepository temp, Basket b )
        {
            repo = temp;
            basket = b;
        }

        // check out 
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }

    }
}

Pages/AddToCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Infrastructure;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore.Pages
{
    public class AddToCartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public AddToCartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public Basket basket {get; set;}
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            //basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
            basket.AddItem(b, 1);

            //HttpContext.Session.SetJson("basket", basket);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage( new {ReturnUrl = returnUrl});
        }
    }
}

Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/AddToCart.cshtml
@page
@model Bookstore.Pages.AddToCartModel
@{
}

<h2>Your Cart</h2>
@*Table to display cart, books, quantity, and cost*@
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.basket.Items)
            {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@(i.Book.Price)</td>
            <td>@((i.Quantity * i.Book.Price).ToString("c")) </td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>
        </tr>
            }
    </tbody>

    @*calculate totals*@
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

@*button to return to previous page*@
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Pages/PurchaseCompleted.cshtml
@page
@model Bookstore.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Transaction complete.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/_AddLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>

@*nav bar*@
<body>
    <div class="m-md-auto">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a asp-controller="Home" asp-action="Index" asp-route-bookCategory="" class="navbar-brand">
                    <img src="~/book-store-logo.png" width="30" height="30" alt="BookStore logo">
                    BookStore
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </div>

    <div class="row m-1 p-1">
            <main>
                @RenderBody()
            </main>
    </div>
</body>
</html>